repos:
  - repo: local
    hooks:
      - id: promptfoo-check
        name: Run promptfoo eval
        entry: bash -c 'promptfoo eval'
        # entry: bash -c 'set -a && source .env && set +a && promptfoo eval'
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        stages: [pre-commit]
