providers:
  - id: openai:gpt-4o
    # optional: set API key via env var OPENAI_API_KEY

#  - id: litellm:gpt-3.5-turbo
#    config:
#      apiBaseUrl: https://litellm.keener.us
#      apiKey: your-api-key # Optional

tests:
  - path: tests/summarization.test.yaml
